=== genepattern/genepattern-server/module-doc/dtd/module_doc.dtd
<!-- DTD for the GenePattern module documentation -->

<!ELEMENT module_doc (name, author?, contact?, summary, overview?, interpretation?, input_parameters?, output_files?, dependencies?, references?)>
<!ELEMENT name (#PCDATA)><!ELEMENT author (#PCDATA)><!ELEMENT contact (#PCDATA)>
<!-- one-line summary used for tooltips; not included in doc -->
<!ELEMENT summary (#PCDATA)>
<!-- description element is used when a description can contain HTML and/or images -->
<!ELEMENT description (text, image_file*)>
<!-- content of text element will be <![CDATA[stuff]]> -->
<!ELEMENT text (#PCDATA)>
<!-- image_file holds a file name; user uploads a file we put file name here and file in images folder -->
<!ELEMENT image_file (#PCDATA)>	
<!-- overview is the Description section in the doc --><!ELEMENT overview (description)>
<!-- interpretation is the Interpreting Results section --><!ELEMENT interpretation (description)><!ELEMENT input_parameters (parameter+)>
<!-- this allows a paremeter description to have multiple example files; typically there'd be one --><!ELEMENT parameter (description, choices?, example_file*)> <!-- example_file holds a file name; user uploads a file we put file name here and file in linked_files folder -->
<!ELEMENT example_file (#PCDATA)><!-- GET ALL parameter ATTRIBUTES EXCEPT TYPE FROM GenePattern -->
<!-- I've left these attributes rather than elements since most will likely be removed from the DTD --><!ATTLIST parameter								type (basic | advanced) #REQUIRED	name CDATA #REQUIRED	default CDATA #IMPLIED	required (yes | no) #REQUIRED	file_format CDATA #IMPLIED><!-- where parameter has choices we want to list them in the doc, descriptions are optional -->
<!ELEMENT choices (choice+)><!ELEMENT choice (value, description?)>
<!-- GET the choice values FROM GenePattern -->
<!ELEMENT value (#PCDATA)>				<!ELEMENT output_files (output_file+)><!ELEMENT output_file (description, example_file*)>
<!ATTLIST output_file								name CDATA #REQUIRED	file_format CDATA #IMPLIED><!-- GET DEPENDENCIES FROM  FROM GenePattern -->
<!ELEMENT dependencies (cpu, os, language, language_version)><!ELEMENT cpu (#PCDATA)><!ELEMENT os (#PCDATA)><!ELEMENT language (#PCDATA)><!ELEMENT language_version (#PCDATA)><!ELEMENT references (reference+)><!-- content of reference element will be <![CDATA[stuff]]> -->
<!ELEMENT reference (#PCDATA)>

=== genepattern/genepattern-server/module-doc/cms/cms.xml
<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" href="../xsl/module_doc.xslt"?>

<!DOCTYPE module_doc SYSTEM "../dtd/module_doc.dtd">

<module_doc>
<name>
ComparativeMarkerSelection
</name>
<author>
Joshua Gould, Gad Getz, Stefano Monti (Broad Institute)
</author>
<contact>
gp-help (at) broad.mit.edu
</contact>
<summary>
Identifies genes that are differentially expressed between distinct classes of samples.
</summary>
<overview>
<description><text><![CDATA[
Identifies genes (if any) that are differentially expressed between distinct classes of samples. For each gene, uses a test statistic to calculate the difference in gene expression between the two classes and computes a p-value to estimate the significance of the test statistic score. Testing tens of thousands of genes simultaneously increases the possibility of mistakenly identifying a non-marker gene as a marker gene (a false positive). Therefore, the module corrects for multiple hypothesis testing by computing both false discovery rates (FDR) and family-wise error rates (FWER).
<ul>
<li>FDR represents the expected proportion of non-marker genes (false positives) within the set of genes declared to be differentially expressed. Researchers generally identify marker genes based on FDR rather than the more conservative FWER.</li>
<li>FWER represents the probability of having any false positive. It is in general stricter or more conservative than FDR. Thus, FWER may frequently fail to find marker genes due to the noisy nature of microarray data and the large number of hypotheses being tested.</li>
</ul>]]></text></description>
</overview>
<interpretation>
<description><text><![CDATA[
<p>Use the ComparativeMarkerSelectionViewer to view the result file. A paragraph discussing what to look for and how to interpret what you find. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent fermentum turpis commodo lorem luctus suscipit. Curabitur adipiscing hendrerit orci. Praesent vitae libero. Suspendisse id turpis in magna rutrum molestie. Quisque tristique mattis purus. Etiam ullamcorper dapibus orci. Vestibulum urna purus, scelerisque in, porta in, molestie semper, odio. Sed sodales ante vel risus. Aenean porttitor pharetra dui. Donec iaculis, velit vel commodo scelerisque, eros est pellentesque nulla, nec aliquet sem nunc non lorem. Sed vitae nisi sit amet metus consectetuer pretium. Donec bibendum urna. Donec commodo, tellus vel egestas condimentum, enim augue elementum mi, at dictum lacus mi eget tortor. Cras dolor.</p>
<p>
If appropriate, discuss next steps. Sed sodales ante vel risus. Aenean porttitor pharetra dui. Donec iaculis, velit vel commodo scelerisque, eros est pellentesque nulla, nec aliquet sem nunc non lorem. Sed vitae nisi sit amet metus consectetuer pretium. Donec bibendum urna. Donec commodo, tellus vel egestas condimentum, enim augue elementum mi, at dictum lacus mi eget tortor. Cras dolor.</p>
]]></text>
<image_file>test.gif</image_file>
<image_file>web_client_tut_cms_viewer.gif</image_file>
</description>
</interpretation>
<input_parameters>
<parameter type = "basic"	name = "input filename"	required = "yes"	file_format = "gct, res">
<description><text><![CDATA[
Gene expression data file. Preprocess the data. Procedures such as FDR and FWER control for multiple hypotheses testing by "inflating" the nominal p-values of the single hypotheses (genes). This allows for controlling the number of false positives but at the cost of potentially increasing the number of false negatives (actual markers that are wrongly declared not differentially expressed). Preprocessing the data reduces the number of hypotheses (genes) to be tested.
]]></text>
</description>
<example_file>all_aml_test.gct</example_file>
</parameter>
<parameter type = "basic"	name = "cls filename"	required = "yes"	file_format = "cls">
<description><text><![CDATA[
Class file
]]></text>
</description>
<example_file>all_aml_test.cls</example_file>
</parameter>
<parameter type = "advanced"	name = "confound variable cls filename"	required = "no"	file_format = "cls">
<description><text><![CDATA[
If you specify this class file, permutations shuffle the labels in <i>Class file</i>  only within the subsets defined by this class file. For example, when identifying genes 
                that are differentially expressed between the classes Tumor and Normal, tissue type 
                might be a confounding variable. This file would define classes for each tissue type. 
                During permutations, the module shuffles the Tumor/Normal labels only among samples that have the same tissue type. 
]]></text>
</description>
</parameter>
<parameter type = "advanced"	name = "test direction"	required = "yes">
<description><text><![CDATA[
The test to perform. 
By default, ComparativeMarkerSelection performs a two-sided test, which tests for differential expression between classes. If you are interested in a one-sided test (up-regulated in class 0 or in class 1), perform the one-sided test, perform the two-sided test, and consider both sets of results.
]]></text>
</description>
<choices>
<choice>
<value>Class 0</value>
<description><text><![CDATA[up-regulated for class 0
]]></text>
</description>
</choice>
<choice>
<value>Class 1</value>
<description><text><![CDATA[up-regulated for class 1
]]></text>
</description>
</choice>
<choice>
<value>Two-sided</value>
<description><text><![CDATA[differentially expressed between class 0 and class 1
]]></text>
</description>
</choice>
</choices>
</parameter>
<parameter type = "advanced"	name = "test statistic"	required = "yes">
<description><text><![CDATA[
The statistic to use.
]]></text>
</description>
<choices>
<choice>
<value>t-test</value>
<description><text><![CDATA[
The difference between the mean expression of class 1 and class 2. Thedifference is divided by the sum of the standard deviation of class 1 and 2 to penalize genes with wide variation. In the equation: 
<ul>
<li>μ is the average<li>σ is the standard deviation<li>n is the number of samples
</ul>
]]></text>
<image_file>t-test.gif</image_file>
</description>
</choice>
<choice>
<value>t-test (median)</value>
<description><text><![CDATA[
Same as t-test, but uses median rather than average.]]></text>
</description>
</choice>
<choice>
<value>t-test (min std)</value>
<description><text><![CDATA[
Same as t-test, but enforces a minimum value for σ (minimal standard deviation).]]></text>
</description>
</choice><choice>
<value>t-test (median, min std)</value>
<description><text><![CDATA[
Same as t-test, but uses median rather than average and enforces a minimum value for σ (minimal standard deviation).]]></text>
</description>
</choice>
<choice>
<value>SNR (signal-to-noise ratio)</value>
<description><text><![CDATA[
In the equation: 
<ul>
<li>μ is the average<li>σ is the standard deviation</ul>
]]></text>
<image_file>snr.gif</image_file>
</description>
</choice>
<choice>
<value>snr (median)</value>
<description><text><![CDATA[
Same as snr, but uses median rather than average.]]></text>
</description>
</choice>
<choice>
<value>snr (min std)</value>
<description><text><![CDATA[
Same as snr, but enforces a minimum value for σ (minimal standard deviation).]]></text>
</description>
</choice><choice>
<value>snr (median, min std)</value>
<description><text><![CDATA[
Same as snr, but uses median rather than average and enforces a minimum value for σ (minimal standard deviation).]]></text>
</description>
</choice>
</choices>
</parameter>
<parameter type = "advanced"	name = "min std"	required = "no">
<description><text><![CDATA[
Used only if test statistic includes the min std option. If σ is less than min std, σ is set to min std.
]]></text>
</description>
</parameter>
<parameter type = "advanced"	name = "number of permutations"	required = "yes">
<description><text><![CDATA[
The number of permutations to perform (use 0 to calculate asymptotic p-values). The number of permutations you specify depends on the number of hypotheses being tested and the significance level that you want to achieve (3). The greater the number of permutations, the more accurate the p value. 
Generally, if the data set includes at least 10 samples per class, use the default value of 1000 permutations 
      to ensure accurate <i>p</i>-values. If the data set includes fewer than 10 samples in any class, permuting the 
      samples cannot give an accurate <i>p</i>-value; specify 0 permutations to use asymptotic <i>p</i>-values
      instead.]]></text>
</description>
</parameter>
<parameter type = "advanced"	name = "complete"	required = "yes">
<description><text><![CDATA[
Whether to perform all possible permutations. By default, complete is set to no and number of permutations determines the number of permutations performed. If you have a small number of samples, you might want to perform all possible permutations.
]]></text>
</description>
</parameter>
<parameter type = "advanced"	name = "balanced"	required = "yes">
<description><text><![CDATA[
Whether to perform balanced permutations. By default, balanced is set to no and phenotype labels are permuted without regard to the number of samples per phenotype (for example, if your dataset has 12 samples in class 0 and 10 in class 1, any permutation of class 0 has 12 randomly selected samples).<p>If you set balanced to yes,  phenotype labels are permuted by balancing the number of samples per phenotype (for example, if your dataset has 12 samples in class 0 and 10 in class 1, any permutation of class 0 has an equal number of samples from class 0 and class 1. Balancing samples is rarely necessary, but may be useful if your samples are very unevenly distributed across phenotypes.
</p>]]></text>
</description>
</parameter>
<parameter type = "advanced"	name = "random seed"	required = "yes">
<description><text><![CDATA[
The seed for the random number generator.]]></text>
</description>
</parameter>
